{"name": "test_div[except]", "status": "failed", "statusDetails": {"message": "AssertionError: assert None == 0\n  +None\n  -0", "trace": "self = <test_calculator.TestCalc object at 0x039BE4F0>, get_calc = <calculator.page.calculator.Calculator object at 0x0395FCB0>\nget_div_datas = [3, 0, 0]\n\n    @pytest.mark.run(order=3)\n    def test_div(self, get_calc, get_div_datas):\n        result = None\n        try:\n            # 调用div函数,返回的结果保存在result里面\n            result = get_calc.div(get_div_datas[0],get_div_datas[1])\n            # 判断result结果是否等于期望的值\n            if isinstance(result, float):\n                result = round(result, 2)\n        except ZeroDivisionError as e:\n            print(e)\n>       assert result == get_div_datas[2]\nE       assert None == 0\nE         +None\nE         -0\n\ntest_calculator.py:40: AssertionError"}, "parameters": [{"name": "get_div_datas", "value": "[3, 0, 0]"}], "start": 1613871860640, "stop": 1613871860640, "uuid": "4e41c016-d63a-4304-8de2-97db585ab218", "historyId": "3a6bf979453b1fb6a7f92f5703879aeb", "testCaseId": "9323664d96830041be80d6c6726e9e46", "fullName": "calculator.TestCase.test_calculator.TestCalc#test_div", "labels": [{"name": "tag", "value": "run(order=3)"}, {"name": "parentSuite", "value": "calculator.TestCase"}, {"name": "suite", "value": "test_calculator"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "DESKTOP-8M4A9CB"}, {"name": "thread", "value": "4312-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "calculator.TestCase.test_calculator"}]}