{"name": "test_mul[except]", "status": "failed", "statusDetails": {"message": "AssertionError: assert '' == '请输入数字'\n  - 请输入数字", "trace": "self = <test_calculator.TestCalc object at 0x0398FF50>, get_calc = <calculator.page.calculator.Calculator object at 0x0395FCB0>\nget_mul_datas = ['', 5, '请输入数字']\n\n    @pytest.mark.run(order=2)\n    # 测试乘法mul函数\n    def test_mul(self, get_calc, get_mul_datas):\n        result = None\n        try:\n            # 调用mul函数,返回的结果保存在result里面\n            result = get_calc.mul(get_mul_datas[0],get_mul_datas[1])\n            # 判断result结果是否等于期望的值\n            if isinstance(result, float):\n                result = round(result, 2)\n        except Exception as e:\n            print(e)\n>       assert result == get_mul_datas[2]\nE       AssertionError: assert '' == '请输入数字'\nE         - 请输入数字\n\ntest_calculator.py:68: AssertionError"}, "parameters": [{"name": "get_mul_datas", "value": "['', 5, '请输入数字']"}], "start": 1613871860548, "stop": 1613871860551, "uuid": "f196f48c-12dc-4466-aee4-7727b6da1461", "historyId": "db45127b964a8bd3921dd13a19d70c6a", "testCaseId": "9a3eaafcbf4ee8431c4dfb6bfd67e674", "fullName": "calculator.TestCase.test_calculator.TestCalc#test_mul", "labels": [{"name": "tag", "value": "run(order=2)"}, {"name": "parentSuite", "value": "calculator.TestCase"}, {"name": "suite", "value": "test_calculator"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "DESKTOP-8M4A9CB"}, {"name": "thread", "value": "4312-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "calculator.TestCase.test_calculator"}]}